apiVersion: batch/v1
kind: Job
metadata: # kpt-merge: kubeflow/katib-cert-generator
  name: katib-cert-generator
  namespace: kubeflow
  labels:
    katib.kubeflow.org/component: cert-generator
  annotations:
    internal.kpt.dev/upstream-identifier: 'batch|Job|kubeflow|katib-cert-generator'
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: katib-cert-generator
      containers:
        - name: cert-generator
          image: docker.io/kubeflowkatib/cert-generator
          command: ["./katib-cert-generator"]
          args: ["generate", "--namespace=$(KATIB_CORE_NAMESPACE)"]
          env:
            - name: KATIB_CORE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: Never
  backoffLimit: 4
