apiVersion: v1
kind: Service
metadata: # kpt-merge: /minio
  name: minio
  labels:
    app: minio
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|minio'
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
