apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      multiCluster:
        # Provided to ensure a human readable name rather than a UUID.
        clusterName: "cn-helical-cursor-270620-us-central1-b-kubeflow" # {"$ref":"#/definitions/io.k8s.cli.substitutions.cluster-name"}
