apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucketAccessControl
metadata:
  name: kubeflow-kfp-gcs-acl # kpt-set: ${name}-kfp-gcs-acl
spec:
  bucketRef:
    name: helical-cursor-270620-kfp # kpt-set: ${bucket-name}
  entity: user-kubeflow-user@helical-cursor-270620.iam.gserviceaccount.com # kpt-set: user-${name}-user@${gcloud.core.project}.iam.gserviceaccount.com
  role: OWNER
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: kubeflow-kfp-gcs-wi-user # kpt-set: ${name}-kfp-gcs-wi-user
spec:
  member: serviceAccount:helical-cursor-270620.svc.id.goog[kubeflow/kubeflow-pipelines-minio-gcs-gateway] # kpt-set: serviceAccount:${gcloud.core.project}.svc.id.goog[kubeflow/kubeflow-pipelines-minio-gcs-gateway]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: kubeflow-user # kpt-set: ${name}-user
